version: '2'
services:
    raspiano-app:
        image: raspiano
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://raspiano-mysql:3306/raspiano?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    raspiano-mysql:
        extends:
            file: mysql.yml
            service: raspiano-mysql
